databases:
  - name: flooz
    databaseName: flooz
    user: flooz

services:
  - type: web
    name: flooz
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flooz
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false